FROM postgres:12.3

# apt-get install
RUN apt-get update \
    && apt-get install wget -y \
    && apt-get install postgresql-12-postgis-3 -y \
    && apt-get install postgis -y
    
COPY ./db.sql /docker-entrypoint-initdb.d/
