version: '3.1'

services:
  db:
    image: postgres:12.3
    container_name: forest_fire_climate_db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.climate-database
      network: host
    user: root
    environment:
      POSTGRES_PASSWORD: ffmodeling
      POSTGRES_USER: adminff
      POSTGRES_DB: ff
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes: 
      - ./DB:/var/lib/postgresql/data:Z
