version: '3.1'

services:
  db:
    image: postgres:12.3
    container_name: climate-database
    build:
      context: .
      dockerfile: Dockerfile.climate-database
    user: "1003:1003"
    environment:
      POSTGRES_PASSWORD: lightning
      POSTGRES_USER: mutakabbir
      POSTGRES_DB: climate
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes: 
      - /data/mutakabbir/Lightning/climate/DB:/var/lib/postgresql/data:Z
